---
Name: approutes
After: framework/_config/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'getCSRFToken': 'NZTA\SDLT\Controller\GraphQLTokenController'
    'vendorApp': 'NZTA\SDLT\Controller\VendorPageController'
    'businessOwnerApproval': 'NZTA\SDLT\Controller\BusinessOwnerApprovalPageController'
